name: Commits
on:
  - pull_request

permissions:
  contents: read

jobs:
  commits:
    name: Canonical CLA signed
    runs-on: ubuntu-22.04
    steps:
    - name: Check if CLA signed
      uses: canonical/has-signed-canonical-cla@1c20438ad54b4d37105e777000545881d2293ba4 # 2.2.0
